export default {
  login: 'zulianperdana',
  id: 58700418,
  node_id: 'MDQ6VXNlcjU4NzAwNDE4',
  avatar_url: 'https://avatars3.githubusercontent.com/u/58700418?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/zulianperdana',
  html_url: 'https://github.com/zulianperdana',
  followers_url: 'https://api.github.com/users/zulianperdana/followers',
  following_url:
    'https://api.github.com/users/zulianperdana/following{/other_user}',
  gists_url: 'https://api.github.com/users/zulianperdana/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/zulianperdana/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/zulianperdana/subscriptions',
  organizations_url: 'https://api.github.com/users/zulianperdana/orgs',
  repos_url: 'https://api.github.com/users/zulianperdana/repos',
  events_url: 'https://api.github.com/users/zulianperdana/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/zulianperdana/received_events',
  type: 'User',
  site_admin: false,
  name: null,
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 4,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2019-12-09T16:34:49Z',
  updated_at: '2020-08-30T08:25:58Z',
};
